### ISSUE TITLE
How to run Image_Gen Script?

### ISSUE THREAD

**Issue by hockeybro12** [alsuhr-c/nlvr-baselines#1]
Hello,

Can you provide an example of how to run the image_gen.js script to create new environments with objects and their JSON representations? If it is already written somewhere, can you let me know (as I can't find it).

Thanks

**Comment by alsuhr-c** [comment]
Hello,

I believe you can use import the JS script in an HTML canvas (i.e. in an HTML file). But since creating this repo I also reproduced the image generation in python, which should be much easier to use. I just added those scripts under the `generation/` directory. The relative imports may not be set up exactly correctly, but the only files you need are `image_generator.py` and `nlvr_image.py`.

The `generate_images` function in `image_generator.py` constructs a set of four images following the original rules we used to generate image sets. Its argument `image_type_counts` is a dictionary with counts of how may image sets have been generated for Scatter and Tower images individually (and this function will sample an image type so that the counts between the two are roughly equal). You can modify the code so that it always generates one type of image, though. In our original collection, I believe we generated scatter and tower images separately.

It requires the `NLVRImage` class which supports saving as a JSON dictionary, SVG, or PNG (although I don't think I tested the PNG version well, and you will need to keep in mind issues with image quality when generating PNGs).

Please let me know if you have any other questions.
